### PR TITLE
do not use `Buffer` in the browser

### PR DESCRIPTION
**Pull request by D4nte**
Remove the usage of `Buffer` in code executed by both NodeJS and browser.

This removes the need for polyfilling the `Browser` NodeJS built-in in the browser.

### CODE REVIEW

**Comment by martinheidegger** [comment]
Hello @D4nte,

Thank you for the variety of fixes, that are really useful. A separate PR for each would have made merging easier 😅 

The thing I am noticing though is that `./lib.mjs` is [supposed to be replace in the browser]https://github.com/martinheidegger/dns-query/blob/82436fc8bb486d90832f87fa62aae04c5529f421/package.json#L22-L25). So I am wondering in which build tool this doesn't happen. As this seems to be the bigger issue?!

**Comment by D4nte** [comment]
Hi @martinheidegger,

Thank you for the quick response. Will separate the typo fix in another PR.

Regarding the usage of `Buffer`. Indeed I misunderstood the codebase, I need to review. Thank you for pointing this out.

**Comment by D4nte** [comment]
> Thank you for the quick response. Will separate the typo fix in another PR.

Oh I see you already did that :+1:

**Comment by martinheidegger** [comment]
> Thank you for the quick response. Will separate the typo fix in another PR.

Oh, I already cherry-picked the commits, if you don't mind 😅

**Comment by D4nte** [comment]
I think the buffer issue was a keyboard-chair one. Other changes have been extracted. Closing PR.

**Comment by martinheidegger** [comment]
Thank you for the PR still, it is helpful to have response like this! The latest changes have been published as 0.11.2

**Pull request closed without merging**
